name: SonarQube Tests

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest  # 🔴 Changed from 'windows-latest' to 'ubuntu-latest'

    services:
      sonarqube:
        image: sonarqube:lts
        ports:
          - 9000:9000
        options: >-
          --health-cmd "curl -f http://localhost:9000/api/system/health || exit 1"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 10
          -e SONAR_ES_BOOTSTRAP_CHECKS_DISABLE=true
          -e SONARQUBE_JDBC_URL=jdbc:h2:mem:sonar
        env:
          SONAR_ES_BOOTSTRAP_CHECKS_DISABLE: "true"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Wait for SonarQube to be ready
        shell: bash
        run: |
          echo "Waiting for SonarQube..."
          for i in {1..30}; do
            if curl -s http://localhost:9000/api/system/health | grep -q "GREEN"; then
              echo "SonarQube is ready!"
              exit 0
            fi
            sleep 5
          done
          echo "SonarQube did not start in time" && exit 1

      - name: Build & Run Both Tests
        run: |
          ./gradlew clean test --tests "org.sonar.core.util.SonarQubeHealthCheckTest" --tests "org.sonar.core.util.SystemPingIntegrationTest"
